### ISSUE TITLE
scaling 10

### ISSUE THREAD

**Issue by Flohti** [joric/io_scene_b3d#8]
Hi,

Import and export scale model by 10, and it seems that change the value in the option doesn't change anything, 

Thanks so for your work

(sorry if bad english)

**Comment by Poikilos** [comment]
Hmm, this may be due to exporting meshes instead of getting all object scaling.
- @joric, see https://github.com/poikilos/EnlivenMinetest/blob/master/utilities/blender/generate_lua_collisionbox.py which gets all possible sources of scaling--I'm not sure if it will help here or not.
- This issue of using raw meshes is also somewhat related to #7

**Comment by joric** [comment]
I doubt I'd ever fix that now.

**Upd.** I'm not ceased to maintain the original but I'm really not that interested in B3D. I'm not archiving the repo just yet. I've updated the readme here https://github.com/joric/io_scene_b3d

**Comment by Poikilos** [comment]
@Flohti See if the issue still exists on this updated fork: https://github.com/VirtualBrightPlayz/io_scene_b3d

:edit: I think you have to [apply the scale](https://docs.blender.org/manual/en/latest/scene_layout/object/editing/apply.html) to fix the issue.
